web_app/myproject/downloaddata_views/views.py
from flask import Blueprint,render_template,redirect,url_for, session, send_file, make_response
from myproject import db
from myproject.downloaddata_views.forms import QuerytableForm,DCF_Form, PE_Form
from myproject.models import financial,company
import pandas as pd
from flask_restful import Resource
from myproject import api
import re
import yfinance as yf
import sqlite3
import pandas as pd
import datetime



downloaddata_blueprint = Blueprint('downloaddata_views',
                              __name__,
                              template_folder='templates')


@downloaddata_blueprint.route('/download_data', methods=['GET', 'POST'])
def DOWNLOAD_DATA():

    # import form from forms.py
    form = QuerytableForm()

    # message variable is imported from the LIST_COMPANIES view, the variable exists only once this form has been submitted and LIST_COMPANIES view has been run
    try:
        message = session.get('message', None)
    except NameError: # if the session.get('message', None) variable does not exist yet, assign message variable to None
        message = None
    if (message != None):
        session['message'] = None #Set the session variable to None, so that when people go back to this view, it won't show the error message again
        return render_template('download_data.html', form=form, message=message)

    # if button is clicked on the form
    if form.validate_on_submit():
        # collect data from the inputs
        ticker = form.ticker.data.lower()
        fiscal_period = form.year.data

        # test to see if the company exists in the db, if not then return a message
        company_data = company.query.filter_by(instance=ticker).first()
        if company_data is None:
            message = f"The inputted ticker, {ticker}, was not found in the database"
            return render_template('download_data.html', form=form, message=message)
        elif bool(re.search('^[0-9]{1,15}$', str(company_data.ein_id))) == True: #ticker and year variables will be imported to the following view
            return redirect(url_for('downloaddata_views.LIST_COMPANIES', ticker=ticker, fiscal_period=fiscal_period))

    # Connecting to a template (html file)
    return render_template('download_data.html', form=form)


@downloaddata_blueprint.route('/data_query/<ticker>_<fiscal_period>') #the same arguments in the url 'ticker' and 'year' have to be included in the LIST_COMPANIES view function but not required in the return render_template
def LIST_COMPANIES(ticker, fiscal_period):
    try:
        company_data = pd.read_sql_query(f"SELECT * from company where instance = '{ticker}'", db.get_engine())
        company_data["test"] = company_data["fy"].astype(str) + company_data["fp"] #create a new column that combines fy and fp strings; doing this because one ticker can change their unique ein at any quarter
        company_data["test"] = company_data['test'].str.replace('FY','Q4') #replace 'FY' with 'Q4'
        company_data = company_data[company_data["test"] >= fiscal_period]
        print(company_data)
        company_data = company_data.sort_values(by=['test'], ascending=True) #sort the values with earliest fiscal year on top
        company_data = company_data.reset_index(drop=True) #reset the index because you can only subset specific rows as in the following line if index is reset
        company_data = company_data.iloc[[0]]
        print(company_data)
        ein = company_data['ein_id'].values[0] # get the value from the ein_id column

        fiscal_yr = re.sub("Q[0-9]{1}$", "", fiscal_period)
        fiscal_qtr = re.sub("^[0-9]{4}", "", fiscal_period)
        financials = pd.read_sql_query(f"SELECT * from financial where ein_id = '{ein}' and fy = '{fiscal_yr}' and (fq = '{fiscal_qtr}' or fq = 'FY')", db.get_engine())
        if fiscal_qtr == "Q4":
            financials = financials[(financials['qtrs'] == "0") | ((financials['qtrs'] == "4") & (financials['fq'] == "FY"))]
        else:
            financials = financials[financials['qtrs'] == "0"]

        fiscal_date = max(financials["data_date"])
        format_date = datetime.datetime.strptime(fiscal_date, '%Y%m%d') #specify the format of the original data as a datetime object
        fiscal_date = format_date.strftime("%Y-%m-%d")

        # add the ticker and year variables so they are accessible in list.html
        return render_template('list.html', financials=financials, companies=company_data, ticker=ticker, fiscal_period=fiscal_period, fiscal_date=fiscal_date)
    except: #will activate the except clause if there is an error message with the script above, proably meaning there isn't enough data to perform the calculation
        session['message'] = f'The fiscal data period, {fiscal_period}, was not available for the given stock ticker. Input a different fiscal period'
        return redirect(url_for('downloaddata_views.DOWNLOAD_DATA'))


@downloaddata_blueprint.route('/data_query/download_csv/<ticker>_<fiscal_period>')
def DOWNLOAD_CSV(ticker, fiscal_period):
    company_data = pd.read_sql_query(f"SELECT * from company where instance = '{ticker}'", db.get_engine())
    print(company_data)
    company_data["test"] = company_data["fy"].astype(str) + company_data["fp"] #####TESTING
    print(company_data, fiscal_period)
    company_data["test"] = company_data['test'].str.replace('FY','Q4')
    company_data = company_data[company_data["test"] >= fiscal_period]
    print(company_data)
    company_data = company_data.sort_values(by=['test'], ascending=True)

    company_data = company_data.reset_index(drop=True)

    company_data = company_data.iloc[[0]]
    print(company_data)
    ein = company_data['ein_id'].values[0]
    fiscal_yr = re.sub("Q[0-9]{1}$", "", fiscal_period)
    fiscal_qtr = re.sub("^[0-9]{4}", "", fiscal_period)
    # Get data from financial table via sql query
    financials = pd.read_sql_query(f"SELECT * from financial where ein_id = '{ein}' and fy = '{fiscal_yr}' and (fq = '{fiscal_qtr}' or fq = 'FY')", db.get_engine())
    if fiscal_qtr == "Q4":
        df = financials[(financials['qtrs'] == "0") | ((financials['qtrs'] == "4") & (financials['fq'] == "FY"))]
    else:
        df = financials[financials['qtrs'] == "0"]
    # create csv file
    response = make_response(df.to_csv())
    response.headers["Content-Disposition"] = f"attachment; filename={ticker}_{fiscal_period}.csv"
    response.headers["Content-Type"] = "text/csv"
    return response


@downloaddata_blueprint.route('/valuation_models_DCF', methods=['GET', 'POST'])
def VALUATION_MODELS_DCF():
    # import form from forms.py
    form = DCF_Form()

    # message variable is imported from the VALUATION_MODELS_DCF_LIST view, the variable exists only once this form has been submitted and VALUATION_MODELS_DCF_LIST view has been run
    try:
        message = session.get('message', None)
    except NameError: # if the session.get('message', None) variable does not exist yet, assign message variable to None
        message = None
    if (message != None):
        session['message'] = None #Set the session variable to None, so that when people go back to this view, it won't show the error message again
        return render_template('valuation_models_DCF.html', form=form, message=message)

    # if button is clicked on the form
    if form.validate_on_submit():
        # collect data from the inputs; session is used to store the variable so it can be used in another view
        ticker = form.ticker.data.lower()
        growth_rte = form.growth_rte.data
        decline_rte = form.decline_rte.data
        discount_rte = form.discount_rte.data
        terminal_growth_rt = form.terminal_growth_rt.data
        years_project = form.years_project.data
        fiscal_period = form.fiscal_period.data

        # test to see if the company exists in the db, if not then return a message
        company_data = company.query.filter_by(instance=ticker).first()
        if company_data is None:
            message = f"The inputted ticker, {ticker}, was not found in the database"
            return render_template('valuation_models_DCF.html', form=form, message=message)

        #redirect to the following view if the form has been successfully submitted
        return redirect(url_for('downloaddata_views.VALUATION_MODELS_DCF_LIST', ticker=ticker, growth_rte=growth_rte, decline_rte=decline_rte, discount_rte=discount_rte,
        terminal_growth_rt=terminal_growth_rt, years_project=years_project, fiscal_period=fiscal_period))

    return render_template('valuation_models_DCF.html', form=form)


@downloaddata_blueprint.route('/valuation_models_DCF_list/<ticker>_<fiscal_period>_<growth_rte>_<decline_rte>_<discount_rte>_<terminal_growth_rt>_<years_project>', methods=['GET', 'POST'])
def VALUATION_MODELS_DCF_LIST(ticker, fiscal_period, growth_rte, decline_rte, discount_rte, terminal_growth_rt, years_project):
    try:
        # get the ticker variable data stored from VALUATION_MODELS_DCF view
        ticker = ticker
        growth_rte = growth_rte
        decline_rte = decline_rte
        discount_rte = discount_rte
        terminal_growth_rt = terminal_growth_rt
        years_project = years_project
        fiscal_yr = re.sub("Q[0-9]{1}$", "", fiscal_period)
        fiscal_qtr = re.sub("^[0-9]{4}", "", fiscal_period)
        # query database to get desired data frame
        company_df = pd.read_sql_query(f"SELECT * from company where instance = '{ticker}'", db.get_engine())
        company_df["test"] = company_df["fy"].astype(str) + company_df["fp"] #create a new column, this column will be used to sort because one ticker may have multiple ein numbers but each ein has different reporting period
        print(company_df, fiscal_period)
        company_df["test"] = company_df['test'].str.replace('FY','Q4') #replace FY with Q4
        company_df = company_df[company_df["test"] >= fiscal_period]
        company_df = company_df.sort_values(by=['test'], ascending=True)

web_app/myproject/downloaddata_views/templates/add.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Have a puppy that needs to be adopted?</h1>
  <p>Add a new puppy with the form below:</p>
  <form method="POST">
      {# This hidden_tag is a CSRF security feature. #}
      {{ form.hidden_tag() }}
      {{ form.name.label }} {{ form.name() }}
      {{ form.submit() }}
  </form>
</div>
{% endblock %}

web_app/myproject/downloaddata_views/templates/compounding_interest.html
{% extends "base.html" %}
{% block content %}
<title>Financinos</title>
<body>
	<iframe src="https://jamesnacino.shinyapps.io/Compound_Interest/" onload="this.width=screen.width;this.height=screen.height;"></iframe>
</body>
{% endblock %}

web_app/myproject/downloaddata_views/templates/data_manual.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <p class="h3">Data Manual</p>
  <hr class="my-4">

  <p>Important things to note: The data used in this database is from SEC's EDGAR data files. Please visit <a href="https://www.sec.gov/dera/data/financial-statement-data-sets.html" target="_blank"><b>SEC's EDGAR website</b></a> for more information regarding the source data. With this, here are the data definitions for CSV file download:
    <ol>
    <li>record_id - The unique record in the database is referenced by a unique record_id</li>
    <li>tag_sec - Retrieved from EDGAR, description for understanding the specific line item. Description provided by the SEC</li>
    <li>label_sec - Retrieved from EDGAR, similar to 'tag_sec', but this is the original description provided by the company</li>
    <li>report - The report where this data can be found (see url below, input in the url where you see [])</li>
    <li>line - The line in the report to where this data can be found</li>
    <li>stmt - Statement type</li>
    <li>data_date - Date to which the financial statement was filed</li>
    <li>fy - Fiscal year for the financial statement</li>
    <li>fq - Fiscal quarter for the financial statement</li>
    <li>qtrs - A value of '0' means it just includes one quarter (quarterly data). A value of '4' means it includes all four quarters (annual data)</li>
    <li>uom - Unit of measure, e.g. currency, shares, etc.</li>
    <li>tag_renamed - A cleaned description of 'tag_sec'</li>
    <li>value - The value of the record</li>
    <li>line_item - Underscored numbers that were aggregated in the financial statement</li>
    <li>url - The location of the financial report on the EDGAR website.. e.g.: https://www.sec.gov/Archives/edgar/data/789019/000119312510015598/R[report].htm</li>
    <li>ein_id - The unique value which identifies the business entity</li>
    </ol>
  </p>
  <p><b>DISCLAIMER:</b> Before using this database. Please note the following:</p>
  <ol>
    <li><p>There has been limited quality assurance checks on the data because only one person maintains the data and there are over 30 million records.</p></li>
    <li><p>Not all data periods may be available.</p></li>
    <li><p>For the Cash Flow statement's, only Q2 through Q4, quarterly data. This data is programatticaly calculated as I could not find these values directly in SEC's EDGAR data files. For example, company Microsoft,
    if it's Q2 aggregated 'Cash Generated By Financing Activities' value is equal to 100 and it's Q3 aggregated 'Cash Generated By Financing Activities' was 150, then the Q3 value would equal 150-100= 50.
  This is because the values in the cash flow statement were aggregated each quarter in the EDGAR data files. Aggregated meaning, Q3 data in SEC Edgar database would aggregate data from Q1 through Q3.</p</li>
  <li><p>For the Income statement's, only Q4, quarterly data. This data is mostly programatticaly calculated as I often could not find these values directly in SEC's EDGAR data files. For example, company Microsoft,
  if it's Q3 aggregated 'Operating Income' value is equal to 100 and it's Q4 aggregated 'Operating Income' was 150, then the Q4 value would equal 150-100= 50.
Most of the values for the income statement found for Q4 in SEC's EDGAR data files were aggregated data; the data values which were non-aggregated were left alone. Q2 through Q3 income statement data also included aggregated data as well as its
non-aggregated data countepart. Q1 income Statement data was not aggregated.</p></li>
<li><p>The only aggregated data shown in this application is FY (fiscal year) end data. The FY end data for the cash flow and income statements are aggregated values from Q1 through Q4. The fiscal year end data for the balance
sheet equals Q4 data. This is the correct method to display financial statements.</p></li>
<li><p>For the exact cleaning process of the data please visit my <a href="https://github.com/JamesPNacino" target="_blank"><b>github</b></a> as the code there shows how the data was processed.</p></li>
  <ol>
</div>
{% endblock %}

web_app/myproject/downloaddata_views/templates/download_data.html
{% extends "base.html"%}
{% block content %}

<div class="container">
<div class="jumbotron">
<p class="h3">Input any stock ticker to retrieve financial data</p>
<hr class="my-4">
<p class="lead">Note:</p>
<ul><li>Fiscal period '2010Q1' is the earliest data period available</li>
<li>Q4 data period will automatically pull both fourth quarter and fiscal year end data</li>
<li><a href="{{url_for('downloaddata_views.TICKER_SEARCH')}}"><b>Click here</b></a> for the list of available stock tickers</li></ul>
<hr class="my-4">
{% if message %}
<div class="alert alert-danger" role="alert">
<p>{{message}}</p>
</div>
{% endif %}
  <form method="POST">
      {# This hidden_tag is a CSRF security feature. #}
      {{ form.hidden_tag() }}
      <p align="left">{{ form.ticker.label }} {{ form.ticker() }}
	    <span style="float:right;">{{ form.year.label }} {{ form.year() }}</span></p>
      <span style="float:right;">{{ form.submit() }}</span>
  </form>

</div>
<div class="jumbotron">
  <p class="lead"><b>Access data via API</b></p>
  <hr class="my-4">
<p>Get data via following url (no API key needed): </p><ul><li><b>Format:</b> "http://financinos.com/REST/[input_ticker]_[input_fiscal-data-period]"</li>
  <li><b>Example:</b> "https://financinos.com/REST/msft_2010Q3"</li></ul>
</div>
</div>


{% endblock %}

web_app/myproject/downloaddata_views/templates/list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="jumbotron">
  <p class="h3">Here is the company information for your inputted stock ticker</p>
  <hr class="my-4">
    {% for index,value in companies.iterrows() %}
    <p class="lead">Company Name: {{value['name']}}</p>
    <p class="lead">Stock Ticker: {{value.instance}}</p>
    <p class="lead">EIN Number: {{value.ein_id}}</p>
    <p class="lead">Address: {{value.bas1}}, {{value.cityba}}, {{value.stprba}} {{value.countryba}} {{value.zipba}}</p>
    {% endfor %}
    <p class="lead">Fiscal period: {{fiscal_period}} (data released on {{fiscal_date}})</p>

    <div style="display: flex; justify-content: flex-end">
      <div><form action="{{url_for('downloaddata_views.DOWNLOAD_CSV', ticker=ticker, fiscal_period=fiscal_period)}}">
          <input type="submit" value="Download Financials" />
      </form></div><p>&nbsp;</p>
      <div><form action="{{url_for('downloaddata_views.DOWNLOAD_DATA')}}">
            <input type="submit" value="New Query" />
      </form></div>
    </div>

</div>
  <table id="data" class="table table-striped">
    <thead>
      <tr>
        <th>description</th>
		<th>statement</th>
		<th>year</th>
		<th>quarter</th>
        <th>value</th>
		<th>ein_id</th>
      </tr>
    </thead>
    <tbody>
      {% for index,value in financials.iterrows() %}
        <tr>
          <td>{{ value.label_sec }}</td>
          <td>{{ value.stmt }}</td>
		  <td>{{ value.fy }}</td>
		  <td>{{ value.fq }}</td>
		  <td>{{ value.value }}</td>
		  <td>{{ value.ein_id }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function () {
      $('#data').DataTable();
    });
  </script>
{% endblock %}

web_app/myproject/downloaddata_views/templates/ticker_search.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
  <p class="lead">Listed below are the following tickers that are available in this web application. Use the search bar to lookup your desired stock</p>
  </div>
  <table id="data" class="table table-striped">
    <thead>
      <tr>
        <th>Company Name</th>
    		<th>Ticker</th>
        <th>Latest Data Available</th>

      </tr>
    </thead>
    <tbody>
      {% for index,value in ticker_table.iterrows() %}
        <tr>
          <td>{{ value.Company_Name }}</td>
          <td>{{ value.Ticker }}</td>
          <td>{{ value.Latest_Available_Data_Period }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function () {
      $('#data').DataTable();
    });
  </script>
{% endblock %}

web_app/myproject/downloaddata_views/templates/valuation_models_DCF.html
{% extends "base.html"%}
{% block content %}

<div class="container">
<div class="jumbotron">
<p class="h3">Stock Price Valuation via the Discounted Cash Flow Model</p>
<hr class="my-4">
<p class="lead">The Discounted Cash Flow (DCF) model is a valuation model that estimates the value of an investment by taking into account it's expected future cash flows.</p>
{% if message %}
<div class="alert alert-danger" role="alert">
<p>{{message}}</p>
</div>
{% endif %}
  <form method="POST">
      {# This hidden_tag is a CSRF security feature. #}
      {{ form.hidden_tag() }}
      <p align="left">{{ form.ticker.label }} {{ form.ticker() }}
   <span style="float:right;">{{ form.fiscal_period.label }} {{ form.fiscal_period() }}</span>
   </p>
      <p align="left">{{ form.years_project.label }} {{ form.years_project() }}
      <span style="float:right;">{{ form.growth_rte.label }} {{ form.growth_rte() }}</span></p>
      <p align="left">{{ form.decline_rte.label }} {{ form.decline_rte() }}
      <span style="float:right;">{{ form.discount_rte.label }} {{ form.discount_rte() }}</span></p>
      <p align="left">{{ form.terminal_growth_rt.label }} {{ form.terminal_growth_rt() }}</p>
      <span style="float:right;">{{ form.submit() }}</span>
  </form>

</div>
</div>


{% endblock %}

web_app/myproject/downloaddata_views/templates/valuation_models_DCF_list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="jumbotron">
  <p class="h3">Here is the company information and discounted cash flow valuation for your inputted stock ticker</p>
  <hr class="my-4">
    <p class="lead">Company Name: {{company.name[0]}}</p>
    <p class="lead">Stock Ticker: {{company.instance[0]}}</p>
    <p class="lead">EIN Number: {{company.ein_id[0]}}</p>
    <p class="lead">Address: {{company.bas1[0]}}, {{company.cityba[0]}}, {{company.stprba[0]}} {{company.countryba[0]}} {{company.zipba[0]}}</p>
<p class="lead">Fiscal data period used for analysis: {{fiscal_period}}</p>
<p class="lead">Stock price as of {{start_date}} (when the {{fiscal_period}} data was released): <b>{{current_stock_price}}</b></p>
<p class="lead">True value of the stock as of {{start_date}}, based on the DCF model: <b>{{DCF_value}}</b></p>
<p class="lead"><b>{{valuation_message}}</b></p>
<div align="right"><form action="{{url_for('downloaddata_views.VALUATION_MODELS_DCF')}}">
      <input type="submit" value="New Query" />
      </form>
</div>
</div>

  <div class="jumbotron">
  <p class="h4">Steps and calculations used to arrive at the valuation</p>
  <hr class="my-4">
  <p class="lead">1. Input variables and calculations used to arrive at the valuation</p>
  <p>Cash Generated By Operating Activities: {{cash_generated_by_operating_activities}}</p>
  <p>Capital Expenditures: {{capex}}</p>
  <p>Cash and Cash Equivalents: {{cash_equivalents}}</p>
  <p>Long Term Debt (Non-current): {{long_debt}}</p>
  <p>Free Cash Flow: {{free_cash_flow_str}}</p>
  <p>Shares Outstanding: {{shares_outstand}}</p>
  <p>Free Cash Flow Growth Rate: {{expected_growth_rate}}</p>
  <p>Growth Decline Rate (The 'Free Cash Flow Growth Rate' will decline by this % every year): {{growth_decline_rate}}</p>
  <p>Discount Rate: {{discount_rate}}</p>
  <p>Terminal Growth Rate (a value of 2.5-3% is the average growth rate of the economy): {{terminal_growth_rate}}</p>
  <p>Number of years to project future cash flows: {{year_projection}}</p>
  <p class="lead">2. The following table shows the projected free cash flows and the net present value of each of the cash flows. It also shows the formulas used to calculate both values</p>
  </div>
  <table id="data" class="table table-striped">
    <thead>
      <tr>
        <th>year</th>
    		<th>Free Cash Flow (FCF) ($)</th>
    		<th>Net Present Value of FCF ($)</th>
        <th>FCF Formula</th>
        <th>NPV of FCF Formula</th>
      </tr>
    </thead>
    <tbody>
      {% for index,value in cashflow_df.iterrows() %}
        <tr>
          <td>{{ value.year }}</td>
          <td>{{ value.FCF }}</td>
		  <td>{{ value.npv_FCF }}</td>
      <td>{{ value.FCF_formula }}</td>
       <td>{{ value.npv_FCF_formula }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="jumbotron">
  <ul><li><p><a href="https://www.wallstreetprep.com/knowledge/terminal-value/" target="_blank">The growth in perpetuity approach</a> - this is the method used to calculate the stock's terminal FCFs in the table above; the "terminal_value" in the year column. It is the method used to calculate the intrinsic stock price value as shown in steps three and four</p></li>
  <li><p><a href="https://www.wallstreetprep.com/knowledge/terminal-value/" target="_blank">The exit multiple approach</a> - this is an alternative method used to calculate the stock's terminal FCFs. To use this method, simply take the final year's FCF npv and multiply it by a number between 10 to 15.
    In general, it is assumed that a company is sold after year 10. This is the reason why this multiple is usually set between 10 and 15 because it simulates the year at which the company would be sold. To note, it is good to be conservative with our estimates so it is best to avoid setting the mutiple too high. Here are the alternative to steps 3 and 4, for example if you wanted to
  use the exit multiple approach to calculate the company's true stock price value:</p>
  <ul><li>Terminal value = {{final_year_npv_FCF}} (final year FCF NPV) x 12 (simulating the year (multiple) at which the company would be sold) = {{final_year_npv_FCF * 12}}</li>
  <li>3-alternative) Company value = {{company_value_formula_alt}}= {{company_value_alt}}</li>
  <li>4-alternative) Discounted Cash Flow Valuation using exit multiple approach = {{company_value_alt}}(company value) / {{shares_outstand}}(shares outstanding) = <b>${{exit_multiple_valuation}}</b></li></ul></li>
  </ul>
  <p class="lead">3. Next, determining the the true value of the company based on the calculated cash flows.</p>
  <p>Company value = {{company_value_formula}} = <b>{{company_value}}</b></p>
  <p class="lead">4. Finally, get the true value of the stock based on the DCF model.</p>
  <p>Discounted Cash Flow Valuation using growth in perpetuity approach = {{DCF_stock_price_formula}} = <b>{{DCF_value}}</b></p>
  </div>
</div>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function () {
      $('#data').DataTable();
    });
  </script>
{% endblock %}

web_app/myproject/downloaddata_views/templates/valuation_models_PE.html
{% extends "base.html"%}
{% block content %}

<div class="container">
<div class="jumbotron">
<p class="h3">Stock Price Valuation via the Price-Earnings Multiple Model</p>
<hr class="my-4">
<p class="lead">The Price-Earnings Multiple model is a valuation model that projects earnings per share to determine the value of an investment.</p>
{% if message %}
<div class="alert alert-danger" role="alert">
<p>{{message}}</p>
</div>
{% endif %}
  <form method="POST">
      {# This hidden_tag is a CSRF security feature. #}
      {{ form.hidden_tag() }}
      <p align="left">{{ form.ticker.label }} {{ form.ticker() }}
      <span style="float:right;">{{ form.fiscal_period.label }} {{ form.fiscal_period() }}</span></p>
      <p align="left">{{ form.years_project.label }} {{ form.years_project() }}
      <span style="float:right;">{{ form.growth_rte.label }} {{ form.growth_rte() }}</span></p>
      <p align="left">{{ form.discount_rte.label }} {{ form.discount_rte() }}</p>
      <span style="float:right;">{{ form.submit() }}<span style="float:right;">
  </form>

</div>
</div>


{% endblock %}